name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - staging
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest

      - name: Lint with Black
        run: black --check backend/app

      - name: Run tests
        run: pytest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@staging-server \
          "cd /path/to/project && docker-compose pull && docker-compose up -d"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@production-server \
          "cd /path/to/project && docker-compose pull && docker-compose up -d"
